// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUgvlx-NfcBetvIZ5w5g-2WyxBD_K04Zc',
    appId: '1:926593776669:web:15c7e1d8496b87466edaf4',
    messagingSenderId: '926593776669',
    projectId: 'bookswapp-3c1af',
    authDomain: 'bookswapp-3c1af.firebaseapp.com',
    storageBucket: 'bookswapp-3c1af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGHX46qEc8CnHhkNhn13gfIMf1WfIkJKc',
    appId: '1:926593776669:android:41099de59e9060926edaf4',
    messagingSenderId: '926593776669',
    projectId: 'bookswapp-3c1af',
    storageBucket: 'bookswapp-3c1af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvkypFx_ziixNOSiYjSRrCf76GQ4kUKAE',
    appId: '1:926593776669:ios:351db3e4102b11aa6edaf4',
    messagingSenderId: '926593776669',
    projectId: 'bookswapp-3c1af',
    storageBucket: 'bookswapp-3c1af.firebasestorage.app',
    iosBundleId: 'com.example.bookswapDemo',
  );
}
